### ISSUE TITLE
How to handle Merge vars

### ISSUE THREAD

**Issue by ustun** [ericrasmussen/postmonkey#4]
How does one handle merge vars with this? Mailchimp API is kind of silly in that the merge vars has to be sent not as a dictionary, but as separate keywords, and one can't send the following as a keyword argument due to [ and ].

merge_vars[FNAME] = "FOOBAR"

instead of merge_vars = {"FNAME": "FOOBAR"}

**Comment by ericrasmussen** [comment]
Have you tried merge_vars={"FNAME": "FOOBAR"} ? The MailChimp API docs list the merge_vars type as "array", which in php is closer to a python dict than an actual array. If for any reason it doesn't work, you can always unpack a dict with keys in the form "merge_vars[KEY]":

pm.someMethod(foo=bar, baz=quux, **{'merge_vars[FNAME]': 'fname', 'merge_vars[LNAME]': 'lname'})

Let me know which one works for you.

**Comment by ustun** [comment]
Ah, nice trick! I hadn't thought about unpacking, I thougt about passing merge_vars[FNAME] directly as a keyword argument, but that wouldn't work obviously. I think it should work, let me give it a try.

The first suggestion doesn't work though, see https://jamiecurle.co.uk/blog/mailchimp-listsubscribe-request-library/ for details.

**Comment by ericrasmussen** [comment]
Thanks for the link. If unpacking works for now I'll add a merge_vars section to the PostMonkey docs this weekend. I'm also open to extending PostMonkey to offer a higher level interface for merge_vars if you end up writing a couple of helper functions and want to issue a pull request. Otherwise it might take me a while to get to it.

**Comment by ritwikSOP** [comment]
Just noticed this while hunting for a solution to this problem. Mailsnake flattens data from dictionaries in this way:

``` python
def flatten_data(data, parent_key=''):
    items = []
    for k, v in data.items():
        new_key = ('%s[%s]' % (parent_key, k)) if parent_key else k
        if isinstance(v, collections.MutableMapping):
            items.extend(flatten_data(v, new_key).items())
        elif isinstance(v, collections.MutableSequence):
            new_v = []
            for v_item in v:
                new_v.append((len(new_v), v_item))
            items.extend(flatten_data(dict(new_v), new_key).items())
        else:
            items.append((new_key, v))
    return dict(items)
```

This seems to work well for GROUPINGS, which has dictionaries within the merge_vars dictionary.

**Comment by ustun** [comment]
@ericrasmussen That didn't do the trick for some reason. The array is correctly created until the call to `serializePayload' which I think is swallowing or escaping the brackets. Just calling the same endpoint using stock requests post method is fine though, that's why I am thinking the problem is in serializePayload.

**Comment by ericrasmussen** [comment]
@ustun thanks for the follow up. I will dedicate some time to this over the next couple days to come up with a solution/fix. If you find anything in the meantime that works for you, feel free to paste or submit a patch.

@ritwikSOP thanks for the paste. I'm leery of fully general solutions like that unless we know it covers all cases, and with mailchimp's API that can be difficult to assess. At this point I may just create a small merge vars class and docs to make it explicit and testable. In MailChimp's world merge_vars is a distinct data structure, so I'd much rather import and use something like MergeVars(my_dict, label='merge_vars') that will be serialized to json in the format they expect.

**Comment by ericrasmussen** [comment]
OK, had some time to test this on one of my mailchimp accounts, and it's working fine per my first suggestion. Here's an example that works as expected for me:

pm.listSubscribe(id='omitted', email_address='omitted', update_existing=True, merge_vars={'FNAME': 'Eric', 'LNAME': 'Rasmussen'})

A few notes:

1) The linked blog post uses a GET request without a content-type specified, which requires the flat URL encoding of merge_vars (merge_var[foo]=spam&merge_var[bar]=eggs)
2) The fork of Mailsnake with the flatten_data method creates a POST request with content type application/x-www-form-urlencoded, also requiring the flat encoding
3) PostMonkey uses a content-type header of application/json, and the json encoding of a python dict produces the type of object Mailchimp expects

If you view the json example for the listSubscribe function in the official API docs, you'll see that it uses json_encode and then urlencode to produce the string for the request. Here's an interactive example:

php > print_r(json_encode(array('merge_vars'=>array('FNAME'=>'Eric'))));
{"merge_vars":{"FNAME":"Eric"}}
php > print_r(urlencode(json_encode(array('merge_vars'=>array('FNAME'=>'Eric')))));
%7B%22merge_vars%22%3A%7B%22FNAME%22%3A%22Eric%22%7D%7D

Which is what PostMonkey produces given that input in the form of python dicts (excepting the added whitespace from json.dumps and given that dict key ordering is not guaranteed).

I think at this point what I really need to do is add a merge_vars section to the docs to clarify this, because you couldn't otherwise come to this conclusion without understanding a whole lot about Mailchimp's usage of php built-ins, and one of my goals with PostMonkey is to save people from having to do that.

However, @ustun, if you did try this before and it didn't work, please open a new issue with a reproducible example and I will definitely look into it.
